# apps-config/payment-service/values.yaml

image:
  registry: docker.io
  # Dùng ảnh unprivileged để chạy được mọi nơi (tránh lỗi 403 Docker Hub)
  repository: nginxinc/nginx-unprivileged
  tag: alpine

# 1. Khai báo cổng cho Container (Quan trọng)
containerPorts:
  http: 8080

# 2. Cấu hình Service
service:
  type: ClusterIP
  port: 8080
  
  # 3. ĐÂY LÀ CHỖ SỬA LỖI:
  # Phải viết targetPort dưới dạng danh sách (Map) để khớp với Chart gốc
  targetPort:
    http: 8080
    https: 443

# Tắt tính năng thừa
auth:
  enabled: false
prometheus:
  exporter:
    enabled: false
