# 1. Dùng ảnh tương tự (Vì chúng ta đang dùng chung 1 Chart mẫu)
image:
  registry: docker.io
  repository: nginxinc/nginx-unprivileged
  tag: alpine

# 2. Khai báo cổng
containerPorts:
  http: 8080

# 3. Service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  enabled: false

# 4. Đặt tên khác đi để test
extraEnvVars:
  - name: APP_NAME
    value: "Day la Payment Service - Tien ve nhu nuoc"
