# --- CẤU HÌNH CHO USER SERVICE ---
image:
  registry: docker.io
  repository: nginxinc/nginx-unprivileged
  tag: alpine

containerPorts:
  http: 8080

service:
  type: ClusterIP
  port: 8080
  # QUAN TRỌNG: Cấu trúc map để tránh lỗi template
  targetPort:
    http: 8080
    https: 443

auth:
  enabled: false
prometheus:
  exporter:
    enabled: false

# KHÁC BIỆT Ở ĐÂY: Đặt tên để biết đây là User
extraEnvVars:
  - name: APP_NAME
    value: "This is User Service"
