{{- if and .Values.gatewayApi .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.gatewayName }}
      namespace: {{ .Values.gatewayApi.gatewayNamespace }}
  hostnames:
{{- range .Values.gatewayApi.hostnames }}
    - {{ . | quote }}
{{- end }}
  rules:
{{- range .Values.gatewayApi.rules }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .pathPrefix | quote }}
      backendRefs:
        - name: {{ .serviceName }}
          port: {{ .servicePort }}
{{- end }}
{{- end }}
